name: CI - Compilacao MiniMine

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  construcao:
    name: Compilacao Multiplataforma
    runs-on: ubuntu-latest

    steps:
      - name: Checagem do c√≥digo
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Ferramenta de Construcao (Gradle)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      - name: Dar permissao ao Gradlew
        run: chmod +x gradlew

      - name: Gerar Executavel PC
        run: ./gradlew gdx-pc:jar

      - name: Gerar Pacote Android
        run: ./gradlew gdx-android:assembleDebug

      - name: Guardar Artefato PC
        uses: actions/upload-artifact@v4
        with:
          name: MiniMine-Arquivos-PC
          path: gdx-pc/build/libs/*.jar

      - name: Guardar Artefato Android
        uses: actions/upload-artifact@v4
        with:
          name: MiniMine-Arquivo-Android
          path: gdx-android/build/outputs/apk/debug/*.apk
