name: CI - Build MiniMine

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Multiplataforma
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.7'

      - name: Dar permissão ao Gradlew
        run: chmod +x gradlew

      - name: Build Desktop
        run: ./gradlew gdx-pc:build

      - name: Build Android
        run: ./gradlew gdx-android:assembleDebug

      - name: Upload Desktop Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiniMine-Desktop
          path: gdx-pc/build/libs/*.jar

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: MiniMine-Android
          path: gdx-android/build/outputs/apk/debug/*.apk
